ElseraEmlakProjesi/ElseraEmlakProjesi/Models/Foto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElseraEmlakProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int ID { get; set; }
        public string FotoAdi { get; set; }
        public Nullable<short> FotoSirala { get; set; }
        public Nullable<int> ilanID { get; set; }
    
        public virtual ilan ilan { get; set; }
    }
}

ElseraEmlakProjesi/ElseraEmlakProjesi/Areas/Admin/Controllers/FotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElseraEmlakProjesi.Models;
using System.IO;

namespace ElseraEmlakProjesi.Areas.Admin.Controllers
{
    public class FotoController : Controller
    {
        private EmlakVeriTabaniEntities1 db = new EmlakVeriTabaniEntities1();
        public string UploadImage(HttpPostedFileBase image)
        {
            var imagePath = Path.Combine(Server.MapPath("~/Content/images/upload/"), image.FileName);
            var imageUrl = Path.Combine("~/Content/images/upload/", image.FileName);
            while (System.IO.File.Exists(imagePath))
            {
                Random rnd = new Random();
                string fileName = Path.GetFileNameWithoutExtension(image.FileName) + "-" + rnd.Next(0, 999) + Path.GetExtension(image.FileName);
                imagePath = Path.Combine(Server.MapPath("~/Content/images/upload/"), fileName);
                imageUrl = Path.Combine("~/Content/images/upload/", fileName);
            }
            image.SaveAs(imagePath);
            return imageUrl;
        }

        // GET: Admin/Foto
        public ActionResult Index()
        {
            var foto = db.Foto.Include(f => f.ilan);
            return View(foto.ToList());
        }

        // GET: Admin/Foto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Foto foto = db.Foto.Find(id);
            if (foto == null)
            {
                return HttpNotFound();
            }
            return View(foto);
        }

        // GET: Admin/Foto/Create
        public ActionResult Create()
        {
            ViewBag.ilanID = new SelectList(db.ilan, "ID", "Baslik");
            return View();
        }

        // POST: Admin/Foto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FotoSirala,ilanID")] Foto foto, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var imageUrl = UploadImage(image);
                foto.FotoAdi = imageUrl;
                db.Foto.Add(foto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ilanID = new SelectList(db.ilan, "ID", "Baslik", foto.ilanID);
            return View(foto);
        }

        // GET: Admin/Foto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Foto foto = db.Foto.Find(id);
            if (foto == null)
            {
                return HttpNotFound();
            }
            ViewBag.ilanID = new SelectList(db.ilan, "ID", "Baslik", foto.ilanID);
            return View(foto);
        }

        // POST: Admin/Foto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FotoAdi,FotoSirala,ilanID")] Foto foto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(foto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ilanID = new SelectList(db.ilan, "ID", "Baslik", foto.ilanID);
            return View(foto);
        }

        // GET: Admin/Foto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Foto foto = db.Foto.Find(id);
            if (foto == null)
            {
                return HttpNotFound();
            }
            return View(foto);
        }

        // POST: Admin/Foto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Foto foto = db.Foto.Find(id);
            db.Foto.Remove(foto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
 

ElseraEmlakProjesi/ElseraEmlakProjesi/Areas/Admin/Views/Foto/Create.cshtml
@model ElseraEmlakProjesi.Models.Foto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Foto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Foto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FotoAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="form-control" name="image" id="image" accept="image/*" />
                @Html.ValidationMessageFor(model => model.FotoAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoSirala, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoSirala, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoSirala, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ilanID, "ilanID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ilanID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ilanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ElseraEmlakProjesi/ElseraEmlakProjesi/Areas/Admin/Views/Foto/Delete.cshtml
@model ElseraEmlakProjesi.Models.Foto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Foto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FotoAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FotoSirala)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoSirala)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ilan.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ilan.Baslik)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ElseraEmlakProjesi/ElseraEmlakProjesi/Areas/Admin/Views/Foto/Details.cshtml
@model ElseraEmlakProjesi.Models.Foto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Foto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FotoAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FotoSirala)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoSirala)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ilan.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ilan.Baslik)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ElseraEmlakProjesi/ElseraEmlakProjesi/Areas/Admin/Views/Foto/Edit.cshtml
@model ElseraEmlakProjesi.Models.Foto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Foto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FotoAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoSirala, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoSirala, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoSirala, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ilanID, "ilanID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ilanID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ilanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ElseraEmlakProjesi/ElseraEmlakProjesi/Areas/Admin/Views/Foto/Index.cshtml
@model IEnumerable<ElseraEmlakProjesi.Models.Foto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FotoAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FotoSirala)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ilan.Baslik)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="@Url.Content(item.FotoAdi)" class="img-responsive col-xs-4" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FotoSirala)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ilan.Baslik)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>